name: Update Age on Birthday

on:
  schedule:
    - cron: '0 0 7 6 *'
  workflow_dispatch:

jobs:
  update-age:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate new age
        id: calculate-age
        run: |
          BIRTH_YEAR=2004
          BIRTH_MONTH=6
          BIRTH_DAY=7

          CURRENT_YEAR=$(date +'%Y')

          AGE=$((CURRENT_YEAR - BIRTH_YEAR))
          
          echo "AGE=$AGE" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          sed -i "s/- \*\*[0-9]\+ years old\*\*/- **$AGE years old**/" README.md

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
