name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake
        uses: Platane/snk@v2
        with:
          github_user_name: MarconiJunior
          svg_out_path: dist/snake.svg

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Generated snake.svg"
          add: "dist/snake.svg"
